/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        charcoal: {
          50: '#f6f7f9',
          100: '#edeef2',
          200: '#d7d9e2',
          300: '#b4b8c7',
          400: '#8c92a9',
          500: '#6d738d',
          600: '#565b72',
          700: 'rgba(var(--color-border-rgb), <alpha-value>)',
          750: 'rgba(var(--color-border-rgb), <alpha-value>)',
          800: 'rgba(var(--bg-card-rgb), <alpha-value>)',
          850: 'rgba(var(--bg-panel-rgb), <alpha-value>)',
          900: 'rgba(var(--bg-panel-rgb), <alpha-value>)',
          950: 'rgba(var(--bg-app-rgb), <alpha-value>)',
        },
        gold: {
          50: '#fbf9eb',
          100: '#f6f1cd',
          200: 'rgba(var(--color-accent-secondary-rgb), <alpha-value>)',
          300: 'rgba(var(--color-accent-secondary-rgb), <alpha-value>)',
          400: 'rgba(var(--color-accent-rgb), <alpha-value>)',
          500: 'rgba(var(--color-accent-rgb), <alpha-value>)',
          600: 'rgba(var(--color-accent-rgb), <alpha-value>)',
          700: '#7e5d1a',
          800: '#684a1b',
          900: '#583e1b',
        },
        amber: {
          200: 'rgba(var(--color-accent-secondary-rgb), <alpha-value>)',
          300: 'rgba(var(--color-accent-secondary-rgb), <alpha-value>)',
          400: 'rgba(var(--color-accent-rgb), <alpha-value>)',
          500: 'rgba(var(--color-accent-rgb), <alpha-value>)',
          600: 'rgba(var(--color-accent-rgb), <alpha-value>)',
        },
        slate: {
          100: 'rgba(var(--color-text-primary-rgb), <alpha-value>)',
          200: 'rgba(var(--color-text-primary-rgb), <alpha-value>)',
          300: 'rgba(var(--color-text-primary-rgb), <alpha-value>)',
          400: 'rgba(var(--color-text-muted-rgb), <alpha-value>)',
          500: 'rgba(var(--color-text-muted-rgb), <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgba(var(--color-accent-rgb), <alpha-value>)',
          secondary: 'rgba(var(--color-accent-secondary-rgb), <alpha-value>)',
        },
        theme: {
          app: 'rgba(var(--bg-app-rgb), <alpha-value>)',
          panel: 'rgba(var(--bg-panel-rgb), <alpha-value>)',
          header: 'rgba(var(--bg-header-rgb), <alpha-value>)',
          card: 'rgba(var(--bg-card-rgb), <alpha-value>)',
          border: 'rgba(var(--color-border-rgb), <alpha-value>)',
          accent: 'rgba(var(--color-accent-rgb), <alpha-value>)',
          accentSecondary: 'rgba(var(--color-accent-secondary-rgb), <alpha-value>)',
          primary: 'rgba(var(--color-text-primary-rgb), <alpha-value>)',
          muted: 'rgba(var(--color-text-muted-rgb), <alpha-value>)',
        },
      },
      boxShadow: {
        'accent-sm': '0 0 8px rgba(var(--color-accent-rgb), 0.25)',
        'accent-md': '0 0 15px rgba(var(--color-accent-rgb), 0.3)',
        'accent-lg': '0 0 25px rgba(var(--color-accent-rgb), 0.45)',
        'accent-glow': '0 0 20px rgba(var(--color-accent-rgb), 0.35)',
      },
    },
  },
  plugins: [],
};
